### ISSUE TITLE
Question FAQ: Use Without Dictionary

### ISSUE THREAD

**Issue by Oblique82** [gapmiss/kingdom-study-tools-for-obsidian#1]
Thankyou for this project. It is an immense and amazing resource.

I think its particular value is in the Strong Concordance/Lexicon links. For native English speakers, the dictionary is less important - the key challenge being that the dictionary adds 30 000 notes + to a vault which causes issues with sync, mobile device performance, indexing and graph view

As far as I can tell there are no direct links from either the lexicons or the bible chapters themselves therefore I intend to use this resource without the dictionary component.

I just wonder if this will cause any internal linking problems or break any features. Might be worth updating the README/ FAQ with some of this information, which I would have found useful prior to trialling it

thanks again

**Comment by gapmiss** [comment]
@Oblique82 Thank you for the feedback. There are no links, to the Webster's Dictionary, from either the Bible or the Lexicon. So, removing the `dictionary` folder should alleviate your issues. I've also experienced the performance hit due to the number of notes. Might make sense to move the Dictionary to it's own repository/vault. Happy to hear you are finding the tools useful.

**Comment by Oblique82** [comment]
Thanks for your prompt feedback - I really appreciate it

**Comment by Oblique82** [comment]
In further reviewing performance - even with bible and lexicons are you able to use graph view? It seems to freeze my iMac Pro. I am wondering if any settings can be adjusted to make this useful

**Comment by gapmiss** [comment]
> ... are you able to use graph view?
I do not personally use the graph view and have not tested it.
